pub mod types;

pub mod export;
pub mod extract;

mod binding;
mod client;
mod explain;
mod helpers;

#[cfg(test)]
mod tests;

use crate::models::{
    ConnectionParams, ForeignKey, Index, Pagination, QueryResult, RoutineInfo, RoutineParameter,
    TableColumn, TableInfo, TriggerInfo, ViewInfo,
};
use crate::pool_manager::get_postgres_pool;
use binding::{PgValueOptions, bind_pg_value, build_pk_map_predicate};
use client::{execute, format_pg_error, get_client, query_all, query_one};
pub use explain::explain_query;
use extract::extract_value;
use helpers::{
    escape_identifier, extract_base_type, is_implicit_cast_compatible, PG_ENUM_VALUES_SUBQUERY,
};
use tokio_postgres::types::ToSql;

pub async fn get_schemas(params: &ConnectionParams) -> Result<Vec<String>, String> {
    let pool = get_postgres_pool(params).await?;
    let rows = query_all(
        &pool,
        "SELECT schema_name::text FROM information_schema.schemata \
WHERE schema_name NOT IN ('pg_catalog', 'information_schema', 'pg_toast') \
AND schema_name NOT LIKE 'pg_temp_%' \
AND schema_name NOT LIKE 'pg_toast_temp_%' \
ORDER BY schema_name",
        &[],
    )
    .await?;

    Ok(rows
        .iter()
        .map(|r| r.try_get("schema_name").unwrap_or_default())
        .collect())
}

pub async fn get_databases(params: &ConnectionParams) -> Result<Vec<String>, String> {
    let pool = get_postgres_pool(params).await?;
    let rows = query_all(
        &pool,
        "SELECT datname::text FROM pg_database WHERE datistemplate = false ORDER BY datname",
        &[],
    )
    .await?;
    Ok(rows
        .iter()
        .map(|r| r.try_get("datname").unwrap_or_default())
        .collect())
}

pub async fn get_tables(params: &ConnectionParams, schema: &str) -> Result<Vec<TableInfo>, String> {
    log::debug!(
        "PostgreSQL: Fetching tables for database: {} schema: {}",
        params.database,
        schema
    );
    let pool = get_postgres_pool(params).await?;
    let rows = query_all(
        &pool,
        "SELECT table_name::text as name FROM information_schema.tables WHERE table_schema = $1 AND table_type = 'BASE TABLE' ORDER BY table_name ASC",
        &[&schema],
    )
    .await?;
    let tables: Vec<TableInfo> = rows
        .iter()
        .map(|r| TableInfo {
            name: r.try_get("name").unwrap_or_default(),
        })
        .collect();
    log::debug!(
        "PostgreSQL: Found {} tables in {}",
        tables.len(),
        params.database
    );
    Ok(tables)
}

/// Read the `enum_values` aggregate produced by [`PG_ENUM_VALUES_SUBQUERY`] off
/// an introspection row, treating a missing column or NULL as "no enum".
fn row_enum_values(row: &tokio_postgres::Row) -> Option<Vec<String>> {
    row.try_get::<_, Option<Vec<String>>>("enum_values")
        .ok()
        .flatten()
}

pub async fn get_columns(
    params: &ConnectionParams,
    table_name: &str,
    schema: &str,
) -> Result<Vec<TableColumn>, String> {
    let pool = get_postgres_pool(params).await?;

    // Postgres auto increment is usually sequences (nextval) or GENERATED BY DEFAULT/ALWAYS AS IDENTITY
    let query = format!(
        r#"
        SELECT
            c.column_name::text,
            c.data_type::text,
            c.is_nullable::text,
            c.column_default::text,
            c.is_identity::text,
            c.character_maximum_length,
            (SELECT COUNT(*) FROM information_schema.table_constraints tc
             JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
             WHERE tc.constraint_type = 'PRIMARY KEY'
             AND tc.table_schema = c.table_schema
             AND kcu.table_name = c.table_name
             AND kcu.column_name = c.column_name) > 0 as is_pk,
            {PG_ENUM_VALUES_SUBQUERY}
        FROM information_schema.columns c
        WHERE c.table_schema = $1 AND c.table_name = $2
        ORDER BY c.ordinal_position
    "#
    );

    let rows = query_all(&pool, &query, &[&schema, &table_name]).await?;

    Ok(rows
        .iter()
        .map(|r| {
            let null_str: String = r.try_get("is_nullable").unwrap_or_default();
            let is_pk: bool = r.try_get("is_pk").unwrap_or(false);
            let default_val: String = r.try_get("column_default").unwrap_or_default();
            let is_identity: String = r.try_get("is_identity").unwrap_or_default(); // YES/NO
            let character_maximum_length: Option<u64> = r
                .try_get::<_, Option<i64>>("character_maximum_length")
                .ok()
                .flatten()
                .and_then(|v| u64::try_from(v).ok());
            let enum_values = row_enum_values(r);

            let is_auto = is_identity == "YES" || default_val.contains("nextval");

            // Only set default_value if not auto-increment, not empty, and not NULL
            // Filter out NULL defaults (PostgreSQL represents nullable without default as NULL or NULL::type)
            let default_value = if !is_auto
                && !default_val.is_empty()
                && !default_val.eq_ignore_ascii_case("null")
                && !default_val.starts_with("NULL::")
            {
                Some(default_val)
            } else {
                None
            };

            TableColumn {
                name: r.try_get("column_name").unwrap_or_default(),
                data_type: r.try_get("data_type").unwrap_or_default(),
                is_pk,
                is_nullable: null_str == "YES",
                is_auto_increment: is_auto,
                default_value,
                character_maximum_length,
                enum_values,
            }
        })
        .collect())
}

pub async fn get_foreign_keys(
    params: &ConnectionParams,
    table_name: &str,
    schema: &str,
) -> Result<Vec<ForeignKey>, String> {
    let pool = get_postgres_pool(params).await?;

    let query = r#"
        SELECT
            con.conname::text AS constraint_name,
            src_att.attname::text AS column_name,
            ref_nsp.nspname::text AS foreign_schema_name,
            ref_cl.relname::text AS foreign_table_name,
            ref_att.attname::text AS foreign_column_name,
            CASE con.confupdtype
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
            END::text AS update_rule,
            CASE con.confdeltype
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
            END::text AS delete_rule
        FROM pg_constraint con
        JOIN pg_class src_cl ON src_cl.oid = con.conrelid
        JOIN pg_namespace src_nsp ON src_nsp.oid = src_cl.relnamespace
        JOIN pg_class ref_cl ON ref_cl.oid = con.confrelid
        JOIN pg_namespace ref_nsp ON ref_nsp.oid = ref_cl.relnamespace
        JOIN unnest(con.conkey, con.confkey) AS cols(src_attnum, ref_attnum) ON true
        JOIN pg_attribute src_att
            ON src_att.attrelid = src_cl.oid
            AND src_att.attnum = cols.src_attnum
            AND NOT src_att.attisdropped
        JOIN pg_attribute ref_att
            ON ref_att.attrelid = ref_cl.oid
            AND ref_att.attnum = cols.ref_attnum
            AND NOT ref_att.attisdropped
        WHERE con.contype = 'f'
          AND con.conparentid = 0
          AND src_nsp.nspname = $1
          AND src_cl.relname = $2
        ORDER BY con.conname, cols.src_attnum
    "#;

    let rows = query_all(&pool, &query, &[&schema, &table_name]).await?;

    Ok(rows
        .iter()
        .map(|r| ForeignKey {
            name: r.try_get("constraint_name").unwrap_or_default(),
            column_name: r.try_get("column_name").unwrap_or_default(),
            ref_table: r.try_get("foreign_table_name").unwrap_or_default(),
            ref_column: r.try_get("foreign_column_name").unwrap_or_default(),
            on_update: r.try_get("update_rule").ok(),
            on_delete: r.try_get("delete_rule").ok(),
        })
        .collect())
}

// Batch function: Get all columns for all tables in one query
pub async fn get_all_columns_batch(
    params: &ConnectionParams,
    schema: &str,
) -> Result<std::collections::HashMap<String, Vec<TableColumn>>, String> {
    use std::collections::HashMap;
    let pool = get_postgres_pool(params).await?;

    let query = format!(
        r#"
        SELECT
            c.table_name,
            c.column_name,
            c.data_type,
            c.is_nullable,
            c.column_default,
            c.is_identity,
            c.character_maximum_length,
            (SELECT COUNT(*) FROM information_schema.table_constraints tc
             JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
             WHERE tc.constraint_type = 'PRIMARY KEY'
             AND tc.table_schema = c.table_schema
             AND kcu.table_name = c.table_name
             AND kcu.column_name = c.column_name) > 0 as is_pk,
            {PG_ENUM_VALUES_SUBQUERY}
        FROM information_schema.columns c
        WHERE c.table_schema = $1
        ORDER BY c.table_name, c.ordinal_position
    "#
    );

    let rows = query_all(&pool, &query, &[&schema]).await?;

    let mut result: HashMap<String, Vec<TableColumn>> = HashMap::new();

    for row in rows {
        let table_name: String = row.try_get("table_name").unwrap_or_default();
        let null_str: String = row.try_get("is_nullable").unwrap_or_default();
        let is_pk: bool = row.try_get("is_pk").unwrap_or(false);
        let default_val: String = row.try_get("column_default").unwrap_or_default();
        let is_identity: String = row.try_get("is_identity").unwrap_or_default();
        let character_maximum_length: Option<u64> = row
            .try_get::<_, Option<i64>>("character_maximum_length")
            .ok()
            .flatten()
            .and_then(|v| u64::try_from(v).ok());
        let enum_values = row_enum_values(&row);

        let is_auto = is_identity == "YES" || default_val.contains("nextval");

        // Only set default_value if not auto-increment, not empty, and not NULL
        // Filter out NULL defaults (PostgreSQL represents nullable without default as NULL or NULL::type)
        let default_value = if !is_auto
            && !default_val.is_empty()
            && !default_val.eq_ignore_ascii_case("null")
            && !default_val.starts_with("NULL::")
        {
            Some(default_val)
        } else {
            None
        };

        let column = TableColumn {
            name: row.try_get("column_name").unwrap_or_default(),
            data_type: row.try_get("data_type").unwrap_or_default(),
            is_pk,
            is_nullable: null_str == "YES",
            is_auto_increment: is_auto,
            default_value,
            character_maximum_length,
            enum_values,
        };

        result
            .entry(table_name)
            .or_insert_with(Vec::new)
            .push(column);
    }

    Ok(result)
}

// Batch function: Get all foreign keys for all tables in one query
pub async fn get_all_foreign_keys_batch(
    params: &ConnectionParams,
    schema: &str,
) -> Result<std::collections::HashMap<String, Vec<ForeignKey>>, String> {
    use std::collections::HashMap;
    let pool = get_postgres_pool(params).await?;

    let query = r#"
        SELECT
            src_cl.relname::text AS table_name,
            con.conname::text AS constraint_name,
            src_att.attname::text AS column_name,
            ref_nsp.nspname::text AS foreign_schema_name,
            ref_cl.relname::text AS foreign_table_name,
            ref_att.attname::text AS foreign_column_name,
            CASE con.confupdtype
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
            END::text AS update_rule,
            CASE con.confdeltype
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
            END::text AS delete_rule
        FROM pg_constraint con
        JOIN pg_class src_cl ON src_cl.oid = con.conrelid
        JOIN pg_namespace src_nsp ON src_nsp.oid = src_cl.relnamespace
        JOIN pg_class ref_cl ON ref_cl.oid = con.confrelid
        JOIN pg_namespace ref_nsp ON ref_nsp.oid = ref_cl.relnamespace
        JOIN unnest(con.conkey, con.confkey) AS cols(src_attnum, ref_attnum) ON true
        JOIN pg_attribute src_att
            ON src_att.attrelid = src_cl.oid
            AND src_att.attnum = cols.src_attnum
            AND NOT src_att.attisdropped
        JOIN pg_attribute ref_att
            ON ref_att.attrelid = ref_cl.oid
            AND ref_att.attnum = cols.ref_attnum
            AND NOT ref_att.attisdropped
        WHERE con.contype = 'f'
        AND con.conparentid = 0
        AND src_nsp.nspname = $1
        ORDER BY src_cl.relname, con.conname, cols.src_attnum
    "#;

    let rows = query_all(&pool, &query, &[&schema]).await?;

    let mut result: HashMap<String, Vec<ForeignKey>> = HashMap::new();

    for row in rows {
        let table_name: String = row.try_get("table_name").unwrap_or_default();

        let fk = ForeignKey {
            name: row.try_get("constraint_name").unwrap_or_default(),
            column_name: row.try_get("column_name").unwrap_or_default(),
            ref_table: row.try_get("foreign_table_name").unwrap_or_default(),
            ref_column: row.try_get("foreign_column_name").unwrap_or_default(),
            on_update: row.try_get("update_rule").ok(),
            on_delete: row.try_get("delete_rule").ok(),
        };

        result.entry(table_name).or_insert_with(Vec::new).push(fk);
    }

    Ok(result)
}

pub async fn get_indexes(
    params: &ConnectionParams,
    table_name: &str,
    schema: &str,
) -> Result<Vec<Index>, String> {
    let pool = get_postgres_pool(params).await?;

    let query = r#"
        SELECT
            i.relname as index_name,
            a.attname as column_name,
            ix.indisunique as is_unique,
            ix.indisprimary as is_primary,
            array_position(ix.indkey, a.attnum) as seq_in_index
        FROM
            pg_class t
            JOIN pg_namespace n ON t.relnamespace = n.oid
            JOIN pg_index ix ON t.oid = ix.indrelid
            JOIN pg_class i ON i.oid = ix.indexrelid
            JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(ix.indkey)
        WHERE
            t.relkind = 'r'
            AND n.nspname = $1
            AND t.relname = $2
        ORDER BY
            t.relname,
            i.relname,
            seq_in_index
    "#;

    let rows = query_all(&pool, &query, &[&schema, &table_name]).await?;

    Ok(rows
        .iter()
        .map(|r| Index {
            name: r.try_get("index_name").unwrap_or_default(),
            column_name: r.try_get("column_name").unwrap_or_default(),
            is_unique: r.try_get("is_unique").unwrap_or(false),
            is_primary: r.try_get("is_primary").unwrap_or(false),
            seq_in_index: r.try_get("seq_in_index").unwrap_or(0),
        })
        .collect())
}

pub async fn save_blob_column_to_file(
    params: &ConnectionParams,
    table: &str,
    col_name: &str,
    pk_map: &HashMap<String, serde_json::Value>,
    schema: &str,
    file_path: &str,
) -> Result<(), String> {
    let pool = get_postgres_pool(params).await?;

    let (predicate, pk_params) = build_pk_map_predicate(pk_map, 1)?;
    let query = format!(
        "SELECT \"{}\" FROM \"{}\".\"{}\" WHERE {}",
        escape_identifier(col_name),
        escape_identifier(schema),
        escape_identifier(table),
        predicate,
    );

    let params_ref: Vec<&(dyn ToSql + Sync)> = pk_params
        .iter()
        .map(|b| b.as_ref() as &(dyn ToSql + Sync))
        .collect();
    let row = query_one(&pool, &query, &params_ref).await?;

    let bytes: Vec<u8> = row.try_get(0).map_err(|e| format_pg_error(&e))?;
    std::fs::write(file_path, bytes).map_err(|e| e.to_string())
}

pub async fn fetch_blob_column_as_data_url(
    params: &ConnectionParams,
    table: &str,
    col_name: &str,
    pk_map: &HashMap<String, serde_json::Value>,
    schema: &str,
) -> Result<String, String> {
    let pool = get_postgres_pool(params).await?;

    let (predicate, pk_params) = build_pk_map_predicate(pk_map, 1)?;
    let query = format!(
        "SELECT \"{}\" FROM \"{}\".\"{}\" WHERE {}",
        escape_identifier(col_name),
        escape_identifier(schema),
        escape_identifier(table),
        predicate,
    );

    let params_ref: Vec<&(dyn ToSql + Sync)> = pk_params
        .iter()
        .map(|b| b.as_ref() as &(dyn ToSql + Sync))
        .collect();
    let row = query_one(&pool, &query, &params_ref).await?;

    let bytes: Vec<u8> = row.try_get(0).map_err(|e| format_pg_error(&e))?;
    Ok(crate::drivers::common::encode_blob_full(&bytes))
}

/// Column type metadata used when binding edited cell values.
struct PgColumnType {
    /// `information_schema.columns.data_type` (e.g. `integer`, `USER-DEFINED`).
    data_type: String,
    /// Qualified, double-quoted type to `CAST` string params to when the column
    /// is a user-defined type (enum). `None` for built-in types. See
    /// [`binding::PgValueOptions::user_defined_type`].
    cast_target: Option<String>,
}

/// Fetch `data_type` (and, for user-defined types, the qualified type name) for
/// every column of `schema.table`, keyed by column name. Used by update/insert
/// so enum columns can be cast and numeric/json columns bound correctly.
async fn get_table_column_types(
    pool: &deadpool_postgres::Pool,
    schema: &str,
    table: &str,
) -> Result<std::collections::HashMap<String, PgColumnType>, String> {
    let rows = query_all(
        pool,
        "SELECT column_name::text, data_type::text, udt_schema::text, udt_name::text \
FROM information_schema.columns \
WHERE table_schema = $1 AND table_name = $2",
        &[&schema, &table],
    )
    .await?;

    let mut map = std::collections::HashMap::with_capacity(rows.len());
    for row in &rows {
        let name = match row.try_get::<_, String>("column_name") {
            Ok(name) => name,
            Err(_) => continue,
        };
        let data_type = row
            .try_get::<_, String>("data_type")
            .unwrap_or_else(|_| "unknown".to_string());
        let cast_target = if data_type == "USER-DEFINED" {
            match (
                row.try_get::<_, String>("udt_schema"),
                row.try_get::<_, String>("udt_name"),
            ) {
                (Ok(udt_schema), Ok(udt_name)) => Some(format!(
                    "\"{}\".\"{}\"",
                    escape_identifier(&udt_schema),
                    escape_identifier(&udt_name)
                )),
                _ => None,
            }
        } else {
            None
        };
        map.insert(
            name,
            PgColumnType {
                data_type,
                cast_target,
            },
        );
    }
    Ok(map)
}

fn json_value_kind(value: &serde_json::Value) -> &'static str {
    match value {
        serde_json::Value::Null => "null",
        serde_json::Value::Bool(_) => "boolean",
        serde_json::Value::Number(_) => "number",
        serde_json::Value::String(_) => "string",
        serde_json::Value::Array(_) => "array",
        serde_json::Value::Object(_) => "object",
    }
}

fn update_record_error_context(
    err: String,
    schema: &str,
    table: &str,
    pk_col: &str,
    pk_val: &serde_json::Value,
    col_name: &str,
    new_val: &serde_json::Value,
    column_type: Option<&str>,
    query: &str,
) -> String {
    let column_type = column_type.unwrap_or("unknown");
    let hint = if matches!(new_val, serde_json::Value::String(_))
        && matches!(
            column_type.to_ascii_lowercase().as_str(),
            "smallint"
                | "integer"
                | "bigint"
                | "int2"
                | "int4"
                | "int8"
                | "serial"
                | "bigserial"
                | "numeric"
                | "decimal"
                | "real"
                | "double precision"
                | "float4"
                | "float8"
        ) {
        "\nHint: the edited value arrived from the grid as a JSON string. For numeric PostgreSQL columns, Tabularis attempts to parse it before binding; check that the value is valid for the target column type."
    } else {
        ""
    };

    format!(
        "{err}\n\nPostgreSQL update context:\n- table: \"{schema}\".\"{table}\"\n- column: \"{col_name}\" ({column_type})\n- new value JSON type: {new_val_kind}\n- primary key: \"{pk_col}\" JSON type {pk_val_kind}\n- SQL: {query}{hint}",
        new_val_kind = json_value_kind(new_val),
        pk_val_kind = json_value_kind(pk_val),
    )
}

pub async fn delete_record(
    params: &ConnectionParams,
    table: &str,
    pk_map: &HashMap<String, serde_json::Value>,
    schema: &str,
) -> Result<u64, String> {
    let pool = get_postgres_pool(params).await?;

    let (predicate, pk_params) = build_pk_map_predicate(pk_map, 1)?;
    let query = format!(
        "DELETE FROM \"{}\".\"{}\" WHERE {}",
        escape_identifier(schema),
        escape_identifier(table),
        predicate,
    );

    let params_ref: Vec<&(dyn ToSql + Sync)> = pk_params
        .iter()
        .map(|b| b.as_ref() as &(dyn ToSql + Sync))
        .collect();
    execute(&pool, &query, &params_ref).await
}

pub async fn update_record(
    params: &ConnectionParams,
    table: &str,
    pk_map: &HashMap<String, serde_json::Value>,
    col_name: &str,
    new_val: serde_json::Value,
    schema: &str,
    max_blob_size: u64,
) -> Result<u64, String> {
    let pool = get_postgres_pool(params).await?;
    let column_types = match get_table_column_types(&pool, schema, table).await {
        Ok(types) => types,
        Err(err) => {
            log::debug!(
                "Could not load PostgreSQL column metadata for {}.{}: {}",
                schema,
                table,
                err
            );
            std::collections::HashMap::new()
        }
    };
    let column_info = column_types.get(col_name);
    let column_data_type = column_info.map(|c| c.data_type.as_str());
    let new_val_for_context = new_val.clone();
    let pk_map_for_context = pk_map.clone();

    let mut query = format!(
        "UPDATE \"{}\".\"{}\" SET \"{}\" = ",
        escape_identifier(schema),
        escape_identifier(table),
        escape_identifier(col_name)
    );

    let mut bound_params: Vec<Box<dyn tokio_postgres::types::ToSql + Send + Sync>> = Vec::new();

    let bound = bind_pg_value(
        new_val,
        bound_params.len() + 1,
        PgValueOptions {
            column_type: column_data_type,
            user_defined_type: column_info.and_then(|c| c.cast_target.as_deref()),
            max_blob_size,
            allow_default: true,
        },
    )?;
    query.push_str(&bound.sql);
    if let Some(param) = bound.param {
        bound_params.push(param);
    }

    let (predicate, pk_params) = build_pk_map_predicate(pk_map, bound_params.len() + 1)?;
    query.push_str(" WHERE ");
    query.push_str(&predicate);
    bound_params.extend(pk_params);

    let params_ref: Vec<&(dyn ToSql + Sync)> = bound_params
        .iter()
        .map(|b| b.as_ref() as &(dyn ToSql + Sync))
        .collect();

    let first_pk_col = {
        let mut keys: Vec<&String> = pk_map_for_context.keys().collect();
        keys.sort();
        keys.first().map(|k| k.as_str()).unwrap_or("")
    };
    let first_pk_val = pk_map_for_context
        .get(first_pk_col)
        .cloned()
        .unwrap_or(serde_json::Value::Null);

    execute(&pool, &query, &params_ref).await.map_err(|err| {
        update_record_error_context(
            err,
            schema,
            table,
            first_pk_col,
            &first_pk_val,
            col_name,
            &new_val_for_context,
            column_data_type,
            &query,
        )
    })
}

pub async fn insert_record(
    params: &ConnectionParams,
    table: &str,
    data: std::collections::HashMap<String, serde_json::Value>,
    schema: &str,
    max_blob_size: u64,
) -> Result<u64, String> {
    let pool = get_postgres_pool(params).await?;

    // Preserve original column ordering for stable SQL (collect from HashMap once)
    let mut entries: Vec<(String, serde_json::Value)> = data.into_iter().collect();

    let mut cols = Vec::with_capacity(entries.len());
    for (name, _) in &entries {
        cols.push(format!("\"{}\"", name));
    }

    // Allow empty inserts for auto-generated values (e.g., auto-increment PKs)
    if cols.is_empty() {
        return execute(
            &pool,
            &format!(
                "INSERT INTO \"{}\".\"{}\" DEFAULT VALUES",
                escape_identifier(schema),
                escape_identifier(table)
            ),
            &[],
        )
        .await;
    };

    // Fetch column types so json/jsonb columns get JSON-aware binding and enum
    // columns are cast rather than bound as bare text params.
    let col_types = match get_table_column_types(&pool, schema, table).await {
        Ok(types) => types,
        Err(err) => {
            log::debug!(
                "Could not load PostgreSQL column metadata for {}.{}: {}",
                schema,
                table,
                err
            );
            std::collections::HashMap::new()
        }
    };

    let mut params: Vec<Box<dyn ToSql + Sync + Send>> = Vec::with_capacity(entries.len());
    let mut vals_set: Vec<String> = Vec::with_capacity(entries.len());

    for (col_name, val) in entries.drain(..) {
        let column_info = col_types.get(&col_name);
        let bound = bind_pg_value(
            val,
            params.len() + 1,
            PgValueOptions {
                column_type: column_info.map(|c| c.data_type.as_str()),
                user_defined_type: column_info.and_then(|c| c.cast_target.as_deref()),
                max_blob_size,
                allow_default: false,
            },
        )?;
        vals_set.push(bound.sql);
        if let Some(param) = bound.param {
            params.push(param);
        }
    }

    let query = format!(
        "INSERT INTO \"{}\".\"{}\" ({}) VALUES ({})",
        escape_identifier(schema),
        escape_identifier(table),
        cols.join(", "),
        vals_set.join(", ")
    );

    let params: Vec<&(dyn ToSql + Sync)> = params
        .iter()
        .map(|b| b.as_ref() as &(dyn ToSql + Sync))
        .collect();

    execute(&pool, &query, &params).await
}

pub async fn get_table_ddl(
    params: &ConnectionParams,
    table_name: &str,
    schema: &str,
) -> Result<String, String> {
    let cols = get_columns(params, table_name, schema).await?;
    if cols.is_empty() {
        return Err(format!("Table {} not found or empty", table_name));
    }

    let mut defs = Vec::new();
    let mut pks = Vec::new();

    for col in cols {
        let mut def = format!("\"{}\" {}", col.name, col.data_type);

        if !col.is_nullable {
            def.push_str(" NOT NULL");
        }

        if col.is_pk {
            pks.push(format!("\"{}\"", col.name));
        }
        defs.push(def);
    }

    if !pks.is_empty() {
        defs.push(format!("PRIMARY KEY ({})", pks.join(", ")));
    }

    Ok(format!(
        "CREATE TABLE \"{}\".\"{}\" (\n  {}\n);",
        escape_identifier(schema),
        escape_identifier(table_name),
        defs.join(",\n  ")
    ))
}

/// Acquires a single PostgreSQL client from the pool and applies the
/// optional `search_path` once. Used by both `execute_query` and
/// `execute_batch`; the latter relies on the schema being set on the
/// shared connection so all statements in the batch see the same
/// search_path.
async fn acquire_pg_client(
    params: &ConnectionParams,
    schema: Option<&str>,
) -> Result<deadpool_postgres::Client, String> {
    let pool = get_postgres_pool(params).await?;
    let client = get_client(&pool).await?;
    if let Some(s) = schema {
        let search_path = format!("SET search_path TO \"{}\"", escape_identifier(s));
        client
            .execute(&search_path, &[])
            .await
            .map_err(|e| format_pg_error(&e))?;
    }
    Ok(client)
}

/// Runs one statement against an already-acquired client. Pulled out of
/// `execute_query` so `execute_batch` can reuse it while keeping a single
/// physical connection open for session-state continuity (`BEGIN`/`COMMIT`,
/// `SET LOCAL`, `CREATE TEMP TABLE`, `LASTVAL()`, `PREPARE`/`EXECUTE`).
async fn exec_on_pg_client(
    client: &tokio_postgres::Client,
    query: &str,
    limit: Option<u32>,
    page: u32,
) -> Result<QueryResult, String> {
    // Non-result-set statements (INSERT/UPDATE/DELETE/DDL) go through
    // `client.execute()` so we can return the real affected-row count.
    // The fetch path below is reserved for SELECT-like statements.
    if !crate::drivers::common::returns_result_set(query) {
        let affected = client
            .execute(query, &[])
            .await
            .map_err(|e| format_pg_error(&e))?;
        return Ok(QueryResult {
            columns: vec![],
            rows: vec![],
            affected_rows: affected,
            truncated: false,
            pagination: None,
        });
    }

    let is_select = crate::drivers::common::is_select_query(query);
    let mut manual_limit = limit;
    let mut truncated = false;

    let (final_query, pagination_meta) = if is_select && limit.is_some() {
        let l = limit.unwrap();
        let data_query = crate::drivers::common::build_paginated_query(query, l, page);
        manual_limit = None;
        (data_query, Some((l, page)))
    } else {
        (query.to_string(), None)
    };

    let pg_params: Vec<i32> = vec![];
    let mut rows_stream = std::pin::pin!(
        client
            .query_raw(&final_query, &pg_params)
            .await
            .map_err(|e| format_pg_error(&e))?
    );

    let mut columns: Vec<String> = Vec::new();
    let mut json_rows = Vec::new();

    use futures::stream::StreamExt;

    while let Some(result) = rows_stream.next().await {
        match result {
            Ok(row) => {
                if columns.is_empty() {
                    columns = row.columns().iter().map(|c| c.name().to_string()).collect();
                }

                if let Some(l) = manual_limit {
                    if json_rows.len() >= l as usize {
                        truncated = true;
                        break;
                    }
                }

                let mut json_row = Vec::new();
                for (i, _) in row.columns().iter().enumerate() {
                    let val = extract_value(&row, i, None);
                    json_row.push(val);
                }
                json_rows.push(json_row);
            }
            Err(e) => return Err(format_pg_error(&e)),
        }
    }

    let pagination = if let Some((page_size, p)) = pagination_meta {
        let has_more = json_rows.len() > page_size as usize;
        if has_more {
            json_rows.truncate(page_size as usize);
        }
        truncated = has_more;
        Some(Pagination {
            page: p,
            page_size,
            total_rows: None,
            has_more,
        })
    } else {
        None
    };

    Ok(QueryResult {
        columns,
        rows: json_rows,
        affected_rows: 0,
        truncated,
        pagination,
    })
}

pub async fn execute_query(
    params: &ConnectionParams,
    query: &str,
    limit: Option<u32>,
    page: u32,
    schema: Option<&str>,
) -> Result<QueryResult, String> {
    let client = acquire_pg_client(params, schema).await?;
    exec_on_pg_client(&client, query, limit, page).await
}

/// Runs a sequence of statements on a single pooled client so
/// session-local state survives across them. Per-statement errors are
/// reported in the slot but do not abort the batch — when the script
/// uses an explicit transaction, PostgreSQL rejects subsequent
/// statements with "current transaction is aborted" until `ROLLBACK`,
/// which surfaces the failure naturally in the per-statement result.
pub async fn execute_batch(
    params: &ConnectionParams,
    queries: &[String],
    limit: Option<u32>,
    page: u32,
    schema: Option<&str>,
    on_progress: Option<&crate::drivers::driver_trait::BatchProgressFn>,
) -> Result<Vec<crate::models::BatchStatementResult>, String> {
    let client = acquire_pg_client(params, schema).await?;
    let mut results = Vec::with_capacity(queries.len());
    for (idx, q) in queries.iter().enumerate() {
        let start = std::time::Instant::now();
        let outcome = exec_on_pg_client(&client, q, limit, page).await;
        let res = crate::models::BatchStatementResult::from_outcome(start, outcome);
        if let Some(cb) = on_progress {
            cb(idx, &res);
        }
        results.push(res);
    }
    Ok(results)
}

pub async fn get_views(params: &ConnectionParams, schema: &str) -> Result<Vec<ViewInfo>, String> {
    log::debug!(
        "PostgreSQL: Fetching views for database: {} schema: {}",
        params.database,
        schema
    );
    let pool = get_postgres_pool(params).await?;
    let rows = query_all(
        &pool,
        "SELECT viewname as name FROM pg_views WHERE schemaname = $1 ORDER BY viewname ASC",
        &[&schema],
    )
    .await?;

    let views: Vec<ViewInfo> = rows
        .iter()
        .map(|r| ViewInfo {
            name: r.try_get("name").unwrap_or_default(),
            definition: None,
        })
        .collect();
    log::debug!(
        "PostgreSQL: Found {} views in {}",
        views.len(),
        params.database
    );
    Ok(views)
}

pub async fn get_view_definition(
    params: &ConnectionParams,
    view_name: &str,
    schema: &str,
) -> Result<String, String> {
    let pool = get_postgres_pool(params).await?;
    let qualified = format!(
        "\"{}\".\"{}\"",
        escape_identifier(schema),
        escape_identifier(view_name)
    );

    let client = pool.get().await.map_err(|e| e.to_string())?;

    let row = client
        .query_one(
            "SELECT pg_get_viewdef($1::regclass, true) as definition",
            &[&qualified],
        )
        .await
        .map_err(|e| format!("Failed to get view definition: {}", e))?;

    let definition: String = row.try_get("definition").unwrap_or_default();
    Ok(format!(
        "CREATE OR REPLACE VIEW {} AS\n{}",
        qualified, definition
    ))
}

pub async fn create_view(
    params: &ConnectionParams,
    view_name: &str,
    definition: &str,
    schema: &str,
) -> Result<(), String> {
    let pool = get_postgres_pool(params).await?;
    let query = format!(
        "CREATE VIEW \"{}\".\"{}\" AS {}",
        escape_identifier(schema),
        escape_identifier(view_name),
        definition
    );

    let client = pool.get().await.map_err(|e| e.to_string())?;
    client
        .execute(&query, &[])
        .await
        .map_err(|e| format!("Failed to create view: {}", e))?;

    Ok(())
}

pub async fn alter_view(
    params: &ConnectionParams,
    view_name: &str,
    definition: &str,
    schema: &str,
) -> Result<(), String> {
    let pool = get_postgres_pool(params).await?;
    let query = format!(
        "CREATE OR REPLACE VIEW \"{}\".\"{}\" AS {}",
        escape_identifier(schema),
        escape_identifier(view_name),
        definition
    );

    let client = pool.get().await.map_err(|e| e.to_string())?;
    client
        .execute(&query, &[])
        .await
        .map_err(|e| format!("Failed to alter view: {}", e))?;

    Ok(())
}

pub async fn drop_view(
    params: &ConnectionParams,
    view_name: &str,
    schema: &str,
) -> Result<(), String> {
    let pool = get_postgres_pool(params).await?;
    let query = format!(
        "DROP VIEW IF EXISTS \"{}\".\"{}\"",
        escape_identifier(schema),
        escape_identifier(view_name)
    );

    let client = pool.get().await.map_err(|e| e.to_string())?;
    client
        .execute(&query, &[])
        .await
        .map_err(|e| format!("Failed to drop view: {}", e))?;

    Ok(())
}

pub async fn get_view_columns(
    params: &ConnectionParams,
    view_name: &str,
    schema: &str,
) -> Result<Vec<TableColumn>, String> {
    let pool = get_postgres_pool(params).await?;

    let query = format!(
        r#"
        SELECT
            c.column_name,
            c.data_type,
            c.is_nullable,
            c.column_default,
            c.is_identity,
            c.character_maximum_length,
            (SELECT COUNT(*) FROM information_schema.table_constraints tc
             JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
             WHERE tc.constraint_type = 'PRIMARY KEY'
             AND tc.table_schema = c.table_schema
             AND kcu.table_name = c.table_name
             AND kcu.column_name = c.column_name) > 0 as is_pk,
            {PG_ENUM_VALUES_SUBQUERY}
        FROM information_schema.columns c
        WHERE c.table_schema = $1 AND c.table_name = $2
        ORDER BY c.ordinal_position
    "#
    );

    let rows = query_all(&pool, &query, &[&schema, &view_name]).await?;

    Ok(rows
        .iter()
        .map(|r| {
            let null_str: String = r.try_get("is_nullable").unwrap_or_default();
            let is_pk: bool = r.try_get("is_pk").unwrap_or(false);
            let default_val: String = r.try_get("column_default").unwrap_or_default();
            let is_identity: String = r.try_get("is_identity").unwrap_or_default();
            let character_maximum_length: Option<u64> = r
                .try_get::<_, Option<i64>>("character_maximum_length")
                .ok()
                .flatten()
                .and_then(|v| u64::try_from(v).ok());
            let enum_values = row_enum_values(r);

            let is_auto = is_identity == "YES" || default_val.contains("nextval");

            // Only set default_value if not auto-increment, not empty, and not NULL
            // Filter out NULL defaults (PostgreSQL represents nullable without default as NULL or NULL::type)
            let default_value = if !is_auto
                && !default_val.is_empty()
                && !default_val.eq_ignore_ascii_case("null")
                && !default_val.starts_with("NULL::")
            {
                Some(default_val)
            } else {
                None
            };

            TableColumn {
                name: r.try_get("column_name").unwrap_or_default(),
                data_type: r.try_get("data_type").unwrap_or_default(),
                is_pk,
                is_nullable: null_str == "YES",
                is_auto_increment: is_auto,
                default_value,
                character_maximum_length,
                enum_values,
            }
        })
        .collect())
}

pub async fn get_routines(
    params: &ConnectionParams,
    schema: &str,
) -> Result<Vec<RoutineInfo>, String> {
    let pool = get_postgres_pool(params).await?;
    let query = r#"
            SELECT proname, prokind
            FROM pg_proc
            WHERE pronamespace = (SELECT oid FROM pg_namespace WHERE nspname = $1)
            AND prokind IN ('f', 'p')
            ORDER BY proname
        "#;

    let rows = query_all(&pool, &query, &[&schema]).await?;

    Ok(rows
        .iter()
        .map(|r| {
            let prokind: i8 = r.try_get("prokind").unwrap_or(b'f' as i8); // f=function, p=procedure
            let routine_type = match prokind as u8 as char {
                'p' => "PROCEDURE",
                _ => "FUNCTION",
            };

            RoutineInfo {
                name: r.try_get("proname").unwrap_or_default(),
                routine_type: routine_type.to_string(),
                definition: None,
            }
        })
        .collect())
}

pub async fn get_routine_parameters(
    params: &ConnectionParams,
    routine_name: &str,
    schema: &str,
) -> Result<Vec<RoutineParameter>, String> {
    let pool = get_postgres_pool(params).await?;

    // 1. Get return type for functions
    let return_type_query = r#"
            SELECT data_type, routine_type
            FROM information_schema.routines
            WHERE routine_schema = $1 AND routine_name = $2
            LIMIT 1
        "#;

    let client = pool.get().await.map_err(|e| e.to_string())?;

    let routine_info = client
        .query_opt(return_type_query, &[&schema, &routine_name])
        .await
        .map_err(|e| format_pg_error(&e))?;

    let mut parameters = Vec::new();

    if let Some(info) = routine_info {
        let routine_type: String = info.try_get("routine_type").unwrap_or_default();
        if routine_type == "FUNCTION" {
            let data_type: String = info.try_get("data_type").unwrap_or_default();
            // Exclude void or trigger returns if not relevant
            if !data_type.eq_ignore_ascii_case("void") && !data_type.eq_ignore_ascii_case("trigger")
            {
                parameters.push(RoutineParameter {
                    name: "".to_string(), // Empty name for return value
                    data_type,
                    mode: "OUT".to_string(),
                    ordinal_position: 0,
                });
            }
        }
    }

    // 2. Get parameters
    let query = r#"
            SELECT p.parameter_name, p.data_type, p.parameter_mode, p.ordinal_position
            FROM information_schema.parameters p
            JOIN information_schema.routines r ON p.specific_name = r.specific_name
            WHERE r.routine_schema = $1 AND r.routine_name = $2
            ORDER BY p.ordinal_position
        "#;

    let rows = client
        .query(query, &[&schema, &routine_name])
        .await
        .map_err(|e| format_pg_error(&e))?;

    parameters.extend(rows.iter().map(|r| RoutineParameter {
        name: r.try_get("parameter_name").unwrap_or_default(),
        data_type: r.try_get("data_type").unwrap_or_default(),
        mode: r.try_get("parameter_mode").unwrap_or_default(),
        ordinal_position: r.try_get("ordinal_position").unwrap_or(0),
    }));

    Ok(parameters)
}

pub async fn get_routine_definition(
    params: &ConnectionParams,
    routine_name: &str,
    _routine_type: &str,
    schema: &str,
) -> Result<String, String> {
    let pool = get_postgres_pool(params).await?;

    let query = r#"
            SELECT pg_get_functiondef(p.oid) as definition
            FROM pg_proc p
            JOIN pg_namespace n ON p.pronamespace = n.oid
            WHERE n.nspname = $1 AND p.proname = $2
            LIMIT 1
        "#;

    let row = query_one(&pool, &query, &[&schema, &routine_name]).await?;

    let definition: String = row.try_get("definition").unwrap_or_default();
    Ok(definition)
}

pub async fn get_triggers(
    params: &ConnectionParams,
    schema: &str,
) -> Result<Vec<TriggerInfo>, String> {
    log::debug!(
        "PostgreSQL: Fetching triggers for database: {} schema: {}",
        params.database,
        schema
    );
    let pool = get_postgres_pool(params).await?;
    let query = r#"
        SELECT
            t.trigger_name AS name,
            t.event_object_table AS table_name,
            string_agg(t.event_manipulation, ' OR ' ORDER BY t.event_manipulation) AS event,
            t.action_timing AS timing
        FROM information_schema.triggers t
        WHERE t.trigger_schema = $1
        GROUP BY t.trigger_name, t.event_object_table, t.action_timing
        ORDER BY t.trigger_name
    "#;
    let rows = query_all(&pool, query, &[&schema]).await?;
    let triggers: Vec<TriggerInfo> = rows
        .iter()
        .map(|r| TriggerInfo {
            name: r.try_get("name").unwrap_or_default(),
            table_name: r.try_get("table_name").unwrap_or_default(),
            event: r.try_get("event").unwrap_or_default(),
            timing: r.try_get("timing").unwrap_or_default(),
            definition: None,
        })
        .collect();
    log::debug!(
        "PostgreSQL: Found {} triggers in {}",
        triggers.len(),
        schema
    );
    Ok(triggers)
}

pub async fn get_trigger_definition(
    params: &ConnectionParams,
    trigger_name: &str,
    table_name: &str,
    schema: &str,
) -> Result<String, String> {
    let pool = get_postgres_pool(params).await?;
    let query = r#"
        SELECT pg_get_triggerdef(t.oid, true) AS definition
        FROM pg_trigger t
        JOIN pg_class c ON t.tgrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE t.tgname = $1
          AND c.relname = $2
          AND n.nspname = $3
          AND NOT t.tgisinternal
        LIMIT 1
    "#;
    let row = query_one(&pool, query, &[&trigger_name, &table_name, &schema]).await?;
    let definition: String = row
        .try_get("definition")
        .map_err(|e| format!("Failed to get trigger definition: {}", e))?;
    Ok(definition)
}

pub async fn create_trigger(
    params: &ConnectionParams,
    trigger_sql: &str,
    _schema: &str,
) -> Result<(), String> {
    let pool = get_postgres_pool(params).await?;
    execute(&pool, trigger_sql, &[])
        .await
        .map_err(|e| format!("Failed to create trigger: {}", e))?;
    Ok(())
}

pub async fn drop_trigger(
    params: &ConnectionParams,
    trigger_name: &str,
    table_name: &str,
    schema: &str,
) -> Result<(), String> {
    let pool = get_postgres_pool(params).await?;
    let sql = format!(
        "DROP TRIGGER IF EXISTS {} ON {}.{}",
        escape_identifier(trigger_name),
        escape_identifier(schema),
        escape_identifier(table_name),
    );
    execute(&pool, &sql, &[])
        .await
        .map_err(|e| format!("Failed to drop trigger: {}", e))?;
    Ok(())
}

// ============================================================
// Plugin wrapper
// ============================================================

use crate::drivers::driver_trait::{DatabaseDriver, DriverCapabilities, PluginManifest, SqlDialect};
use async_trait::async_trait;
use std::collections::HashMap;

pub struct PostgresDriver {
    manifest: PluginManifest,
}

impl PostgresDriver {
    pub fn new() -> Self {
        Self {
            manifest: PluginManifest {
                id: "postgres".to_string(),
                name: "PostgreSQL".to_string(),
                version: "1.0.0".to_string(),
                description: "PostgreSQL databases".to_string(),
                default_port: Some(5432),
                capabilities: DriverCapabilities {
                    schemas: true,
                    views: true,
                    routines: true,
                    file_based: false,
                    folder_based: false,
                    connection_string: true,
                    connection_string_example: "postgres://user:pass@localhost:5432/db".into(),
                    identifier_quote: "\"".into(),
                    alter_primary_key: true,
                    auto_increment_keyword: String::new(),
                    serial_type: "SERIAL".into(),
                    inline_pk: false,
                    alter_column: true,
                    create_foreign_keys: true,
                    no_connection_required: false,
                    manage_tables: true,
                    readonly: false,
                    triggers: true,
                    supports_ssl: true,
                    sql_dialect: SqlDialect::Postgres,
                },
                is_builtin: true,
                default_username: "postgres".to_string(),
                color: "#3b82f6".to_string(),
                icon: "postgres".to_string(),
                settings: vec![],
                ui_extensions: None,
            },
        }
    }

    fn resolve_schema<'a>(&self, schema: Option<&'a str>) -> &'a str {
        schema.unwrap_or("public")
    }
}

#[async_trait]
impl DatabaseDriver for PostgresDriver {
    fn manifest(&self) -> &PluginManifest {
        &self.manifest
    }

    fn get_data_types(&self) -> Vec<crate::models::DataTypeInfo> {
        types::get_data_types()
    }

    fn map_inferred_type(&self, kind: &str) -> String {
        match kind {
            "DATETIME" => "TIMESTAMP".to_string(),
            "JSON" => "JSONB".to_string(),
            other => other.to_string(),
        }
    }

    fn build_connection_url(
        &self,
        params: &crate::models::ConnectionParams,
    ) -> Result<String, String> {
        use urlencoding::encode;
        let user = encode(params.username.as_deref().unwrap_or_default());
        let pass = encode(params.password.as_deref().unwrap_or_default());
        Ok(format!(
            "postgres://{}:{}@{}:{}/{}",
            user,
            pass,
            params.host.as_deref().unwrap_or("localhost"),
            params.port.unwrap_or(5432),
            params.database
        ))
    }

    async fn ping(&self, params: &crate::models::ConnectionParams) -> Result<(), String> {
        let conn_id = params.connection_id.as_deref();
        if !crate::pool_manager::has_pool(params, conn_id).await {
            return Err("No active connection pool".into());
        }
        let pool = crate::pool_manager::get_postgres_pool_with_id(params, conn_id).await?;
        let client = pool
            .get()
            .await
            .map_err(|e| crate::pool_manager::format_error_chain(&e))?;
        client
            .simple_query("SELECT 1")
            .await
            .map_err(|e| crate::pool_manager::format_error_chain(&e))?;
        Ok(())
    }

    async fn get_databases(
        &self,
        params: &crate::models::ConnectionParams,
    ) -> Result<Vec<String>, String> {
        let mut p = params.clone();
        p.database = crate::models::DatabaseSelection::Single("postgres".to_string());
        get_databases(&p).await
    }

    async fn get_schemas(
        &self,
        params: &crate::models::ConnectionParams,
    ) -> Result<Vec<String>, String> {
        get_schemas(params).await
    }

    async fn get_tables(
        &self,
        params: &crate::models::ConnectionParams,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::TableInfo>, String> {
        get_tables(params, self.resolve_schema(schema)).await
    }

    async fn get_columns(
        &self,
        params: &crate::models::ConnectionParams,
        table: &str,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::TableColumn>, String> {
        get_columns(params, table, self.resolve_schema(schema)).await
    }

    async fn get_foreign_keys(
        &self,
        params: &crate::models::ConnectionParams,
        table: &str,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::ForeignKey>, String> {
        get_foreign_keys(params, table, self.resolve_schema(schema)).await
    }

    async fn get_indexes(
        &self,
        params: &crate::models::ConnectionParams,
        table: &str,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::Index>, String> {
        get_indexes(params, table, self.resolve_schema(schema)).await
    }

    async fn get_views(
        &self,
        params: &crate::models::ConnectionParams,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::ViewInfo>, String> {
        get_views(params, self.resolve_schema(schema)).await
    }

    async fn get_view_definition(
        &self,
        params: &crate::models::ConnectionParams,
        view_name: &str,
        schema: Option<&str>,
    ) -> Result<String, String> {
        get_view_definition(params, view_name, self.resolve_schema(schema)).await
    }

    async fn get_view_columns(
        &self,
        params: &crate::models::ConnectionParams,
        view_name: &str,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::TableColumn>, String> {
        get_view_columns(params, view_name, self.resolve_schema(schema)).await
    }

    async fn create_view(
        &self,
        params: &crate::models::ConnectionParams,
        view_name: &str,
        definition: &str,
        schema: Option<&str>,
    ) -> Result<(), String> {
        create_view(params, view_name, definition, self.resolve_schema(schema)).await
    }

    async fn alter_view(
        &self,
        params: &crate::models::ConnectionParams,
        view_name: &str,
        definition: &str,
        schema: Option<&str>,
    ) -> Result<(), String> {
        alter_view(params, view_name, definition, self.resolve_schema(schema)).await
    }

    async fn drop_view(
        &self,
        params: &crate::models::ConnectionParams,
        view_name: &str,
        schema: Option<&str>,
    ) -> Result<(), String> {
        drop_view(params, view_name, self.resolve_schema(schema)).await
    }

    async fn get_routines(
        &self,
        params: &crate::models::ConnectionParams,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::RoutineInfo>, String> {
        get_routines(params, self.resolve_schema(schema)).await
    }

    async fn get_routine_parameters(
        &self,
        params: &crate::models::ConnectionParams,
        routine_name: &str,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::RoutineParameter>, String> {
        get_routine_parameters(params, routine_name, self.resolve_schema(schema)).await
    }

    async fn get_routine_definition(
        &self,
        params: &crate::models::ConnectionParams,
        routine_name: &str,
        routine_type: &str,
        schema: Option<&str>,
    ) -> Result<String, String> {
        get_routine_definition(
            params,
            routine_name,
            routine_type,
            self.resolve_schema(schema),
        )
        .await
    }

    async fn get_triggers(
        &self,
        params: &crate::models::ConnectionParams,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::TriggerInfo>, String> {
        get_triggers(params, self.resolve_schema(schema)).await
    }

    async fn get_trigger_definition(
        &self,
        params: &crate::models::ConnectionParams,
        trigger_name: &str,
        table_name: &str,
        schema: Option<&str>,
    ) -> Result<String, String> {
        get_trigger_definition(params, trigger_name, table_name, self.resolve_schema(schema)).await
    }

    async fn create_trigger(
        &self,
        params: &crate::models::ConnectionParams,
        trigger_sql: &str,
        schema: Option<&str>,
    ) -> Result<(), String> {
        create_trigger(params, trigger_sql, self.resolve_schema(schema)).await
    }

    async fn drop_trigger(
        &self,
        params: &crate::models::ConnectionParams,
        trigger_name: &str,
        table_name: &str,
        schema: Option<&str>,
    ) -> Result<(), String> {
        drop_trigger(params, trigger_name, table_name, self.resolve_schema(schema)).await
    }

    async fn execute_query(
        &self,
        params: &crate::models::ConnectionParams,
        query: &str,
        limit: Option<u32>,
        page: u32,
        schema: Option<&str>,
    ) -> Result<crate::models::QueryResult, String> {
        execute_query(params, query, limit, page, schema).await
    }

    async fn execute_batch(
        &self,
        params: &crate::models::ConnectionParams,
        queries: &[String],
        limit: Option<u32>,
        page: u32,
        schema: Option<&str>,
        on_progress: Option<&crate::drivers::driver_trait::BatchProgressFn>,
    ) -> Result<Vec<crate::models::BatchStatementResult>, String> {
        execute_batch(params, queries, limit, page, schema, on_progress).await
    }

    async fn explain_query(
        &self,
        params: &crate::models::ConnectionParams,
        query: &str,
        analyze: bool,
        schema: Option<&str>,
    ) -> Result<crate::models::ExplainPlan, String> {
        explain_query(params, query, analyze, schema).await
    }

    async fn insert_record(
        &self,
        params: &crate::models::ConnectionParams,
        table: &str,
        data: std::collections::HashMap<String, serde_json::Value>,
        schema: Option<&str>,
        max_blob_size: u64,
    ) -> Result<u64, String> {
        insert_record(
            params,
            table,
            data,
            self.resolve_schema(schema),
            max_blob_size,
        )
        .await
    }

    async fn update_record(
        &self,
        params: &crate::models::ConnectionParams,
        table: &str,
        pk_map: &std::collections::HashMap<String, serde_json::Value>,
        col_name: &str,
        new_val: serde_json::Value,
        schema: Option<&str>,
        max_blob_size: u64,
    ) -> Result<u64, String> {
        update_record(
            params,
            table,
            pk_map,
            col_name,
            new_val,
            self.resolve_schema(schema),
            max_blob_size,
        )
        .await
    }

    async fn delete_record(
        &self,
        params: &crate::models::ConnectionParams,
        table: &str,
        pk_map: &std::collections::HashMap<String, serde_json::Value>,
        schema: Option<&str>,
    ) -> Result<u64, String> {
        delete_record(params, table, pk_map, self.resolve_schema(schema)).await
    }

    async fn save_blob_to_file(
        &self,
        params: &crate::models::ConnectionParams,
        table: &str,
        col_name: &str,
        pk_map: &std::collections::HashMap<String, serde_json::Value>,
        schema: Option<&str>,
        file_path: &str,
    ) -> Result<(), String> {
        save_blob_column_to_file(
            params,
            table,
            col_name,
            pk_map,
            self.resolve_schema(schema),
            file_path,
        )
        .await
    }

    async fn fetch_blob_as_data_url(
        &self,
        params: &crate::models::ConnectionParams,
        table: &str,
        col_name: &str,
        pk_map: &std::collections::HashMap<String, serde_json::Value>,
        schema: Option<&str>,
    ) -> Result<String, String> {
        fetch_blob_column_as_data_url(
            params,
            table,
            col_name,
            pk_map,
            self.resolve_schema(schema),
        )
        .await
    }

    async fn get_create_table_sql(
        &self,
        table_name: &str,
        columns: Vec<crate::models::ColumnDefinition>,
        schema: Option<&str>,
    ) -> Result<Vec<String>, String> {
        let pg_schema = self.resolve_schema(schema);
        let mut col_defs = Vec::new();
        let mut pk_cols = Vec::new();
        for col in &columns {
            let type_str = if col.is_auto_increment {
                let upper = col.data_type.to_uppercase();
                if upper.contains("BIGINT") || upper.contains("BIGSERIAL") {
                    "BIGSERIAL".to_string()
                } else if upper.contains("SMALLINT") || upper.contains("SMALLSERIAL") {
                    "SMALLSERIAL".to_string()
                } else {
                    "SERIAL".to_string()
                }
            } else {
                col.data_type.clone()
            };
            let mut def = format!("\"{}\" {}", col.name.replace('"', "\"\""), type_str);
            if !col.is_nullable && !col.is_auto_increment {
                def.push_str(" NOT NULL");
            }
            if let Some(default) = &col.default_value {
                if !col.is_auto_increment {
                    def.push_str(&format!(" DEFAULT {}", default));
                }
            }
            col_defs.push(def);
            if col.is_pk {
                pk_cols.push(format!("\"{}\"", col.name.replace('"', "\"\"")));
            }
        }
        if !pk_cols.is_empty() {
            col_defs.push(format!("PRIMARY KEY ({})", pk_cols.join(", ")));
        }
        Ok(vec![format!(
            "CREATE TABLE \"{}\".\"{}\" (\n  {}\n)",
            pg_schema.replace('"', "\"\""),
            table_name.replace('"', "\"\""),
            col_defs.join(",\n  ")
        )])
    }

    async fn get_add_column_sql(
        &self,
        table: &str,
        column: crate::models::ColumnDefinition,
        schema: Option<&str>,
    ) -> Result<Vec<String>, String> {
        let pg_schema = self.resolve_schema(schema);
        let tbl = format!(
            "\"{}\".\"{}\"",
            pg_schema.replace('"', "\"\""),
            table.replace('"', "\"\"")
        );
        let type_str = if column.is_auto_increment {
            let upper = column.data_type.to_uppercase();
            if upper.contains("BIGINT") || upper.contains("BIGSERIAL") {
                "BIGSERIAL".to_string()
            } else if upper.contains("SMALLINT") || upper.contains("SMALLSERIAL") {
                "SMALLSERIAL".to_string()
            } else {
                "SERIAL".to_string()
            }
        } else {
            column.data_type.clone()
        };
        let mut def = format!(
            "ALTER TABLE {} ADD COLUMN \"{}\" {}",
            tbl,
            column.name.replace('"', "\"\""),
            type_str
        );
        if !column.is_nullable && !column.is_auto_increment {
            def.push_str(" NOT NULL");
        }
        if let Some(default) = &column.default_value {
            if !column.is_auto_increment {
                def.push_str(&format!(" DEFAULT {}", default));
            }
        }
        Ok(vec![def])
    }

    async fn get_alter_column_sql(
        &self,
        table: &str,
        old_column: crate::models::ColumnDefinition,
        new_column: crate::models::ColumnDefinition,
        schema: Option<&str>,
    ) -> Result<Vec<String>, String> {
        let pg_schema = self.resolve_schema(schema);
        let tbl = format!(
            "\"{}\".\"{}\"",
            pg_schema.replace('"', "\"\""),
            table.replace('"', "\"\"")
        );
        let old_name = format!("\"{}\"", old_column.name.replace('"', "\"\""));
        let new_name_quoted = format!("\"{}\"", new_column.name.replace('"', "\"\""));
        let mut stmts = Vec::new();

        if old_column.name != new_column.name {
            stmts.push(format!(
                "ALTER TABLE {} RENAME COLUMN {} TO {}",
                tbl, old_name, new_name_quoted
            ));
        }

        let col_ref = &new_name_quoted;

        if old_column.data_type != new_column.data_type {
            let old_base = extract_base_type(&old_column.data_type);
            let new_base = extract_base_type(&new_column.data_type);

            if is_implicit_cast_compatible(&old_base, &new_base) {
                stmts.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} TYPE {}",
                    tbl, col_ref, new_column.data_type
                ));
            } else {
                stmts.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} TYPE {} USING {}::{}",
                    tbl, col_ref, new_column.data_type, col_ref, new_column.data_type
                ));
            }
        }

        if old_column.is_nullable != new_column.is_nullable {
            if new_column.is_nullable {
                stmts.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} DROP NOT NULL",
                    tbl, col_ref
                ));
            } else {
                stmts.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} SET NOT NULL",
                    tbl, col_ref
                ));
            }
        }

        if old_column.default_value != new_column.default_value {
            if let Some(default) = &new_column.default_value {
                stmts.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} SET DEFAULT {}",
                    tbl, col_ref, default
                ));
            } else {
                stmts.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} DROP DEFAULT",
                    tbl, col_ref
                ));
            }
        }

        if stmts.is_empty() {
            return Err("No changes detected".into());
        }
        Ok(stmts)
    }

    async fn get_create_index_sql(
        &self,
        table: &str,
        index_name: &str,
        columns: Vec<String>,
        is_unique: bool,
        schema: Option<&str>,
    ) -> Result<Vec<String>, String> {
        let pg_schema = self.resolve_schema(schema);
        let unique = if is_unique { "UNIQUE " } else { "" };
        let cols: Vec<String> = columns
            .iter()
            .map(|c| format!("\"{}\"", c.replace('"', "\"\"")))
            .collect();
        Ok(vec![format!(
            "CREATE {}INDEX \"{}\" ON \"{}\".\"{}\" ({})",
            unique,
            index_name.replace('"', "\"\""),
            pg_schema.replace('"', "\"\""),
            table.replace('"', "\"\""),
            cols.join(", ")
        )])
    }

    async fn get_create_foreign_key_sql(
        &self,
        table: &str,
        fk_name: &str,
        column: &str,
        ref_table: &str,
        ref_column: &str,
        on_delete: Option<&str>,
        on_update: Option<&str>,
        schema: Option<&str>,
    ) -> Result<Vec<String>, String> {
        let pg_schema = self.resolve_schema(schema);
        let tbl = format!(
            "\"{}\".\"{}\"",
            pg_schema.replace('"', "\"\""),
            table.replace('"', "\"\"")
        );
        let mut query = format!(
            "ALTER TABLE {} ADD CONSTRAINT \"{}\" FOREIGN KEY (\"{}\") REFERENCES \"{}\".\"{}\" (\"{}\")",
            tbl,
            fk_name.replace('"', "\"\""),
            column.replace('"', "\"\""),
            pg_schema.replace('"', "\"\""),
            ref_table.replace('"', "\"\""),
            ref_column.replace('"', "\"\"")
        );
        if let Some(action) = on_delete {
            query.push_str(&format!(" ON DELETE {}", action));
        }
        if let Some(action) = on_update {
            query.push_str(&format!(" ON UPDATE {}", action));
        }
        Ok(vec![query])
    }

    async fn drop_index(
        &self,
        params: &crate::models::ConnectionParams,
        _table: &str,
        index_name: &str,
        schema: Option<&str>,
    ) -> Result<(), String> {
        let pg_schema = self.resolve_schema(schema);
        let query = format!(
            "DROP INDEX \"{}\".\"{}\"",
            pg_schema.replace('"', "\"\""),
            index_name.replace('"', "\"\"")
        );
        execute_query(params, &query, None, 1, schema).await?;
        Ok(())
    }

    async fn drop_foreign_key(
        &self,
        params: &crate::models::ConnectionParams,
        table: &str,
        fk_name: &str,
        schema: Option<&str>,
    ) -> Result<(), String> {
        let pg_schema = self.resolve_schema(schema);
        let query = format!(
            "ALTER TABLE \"{}\".\"{}\" DROP CONSTRAINT \"{}\"",
            pg_schema.replace('"', "\"\""),
            table.replace('"', "\"\""),
            fk_name.replace('"', "\"\"")
        );
        execute_query(params, &query, None, 1, schema).await?;
        Ok(())
    }

    async fn get_all_columns_batch(
        &self,
        params: &crate::models::ConnectionParams,
        schema: Option<&str>,
    ) -> Result<HashMap<String, Vec<crate::models::TableColumn>>, String> {
        get_all_columns_batch(params, self.resolve_schema(schema)).await
    }

    async fn get_all_foreign_keys_batch(
        &self,
        params: &crate::models::ConnectionParams,
        schema: Option<&str>,
    ) -> Result<HashMap<String, Vec<crate::models::ForeignKey>>, String> {
        get_all_foreign_keys_batch(params, self.resolve_schema(schema)).await
    }

    async fn get_schema_snapshot(
        &self,
        params: &crate::models::ConnectionParams,
        schema: Option<&str>,
    ) -> Result<Vec<crate::models::TableSchema>, String> {
        let pg_schema = self.resolve_schema(schema);
        let tables = get_tables(params, pg_schema).await?;
        let mut columns_map = get_all_columns_batch(params, pg_schema).await?;
        let mut fks_map = get_all_foreign_keys_batch(params, pg_schema).await?;
        Ok(tables
            .into_iter()
            .map(|t| crate::models::TableSchema {
                name: t.name.clone(),
                columns: columns_map.remove(&t.name).unwrap_or_default(),
                foreign_keys: fks_map.remove(&t.name).unwrap_or_default(),
            })
            .collect())
    }
}
